import * as functions from "firebase-functions";
import * as admin from "firebase-admin";

// Guard against double-init: index.ts already calls initializeApp() before importing this
// module, so an unguarded call here threw "default Firebase app already exists" at module
// load — which broke `firebase deploy` DISCOVERY (it executes the code to enumerate exports),
// leaving the whole functions codebase un-analyzable. Matches analytics/finance/contractExpiry.
if (!admin.apps.length) {
    admin.initializeApp();
}
const db = admin.firestore();

/**
 * Subscription Auto-Billing
 * Runs daily at midnight to create invoices for subscriptions due for billing
 */
export const subscriptionAutoBilling = functions.pubsub
    .schedule("0 0 * * *")
    .timeZone("UTC")
    .onRun(async () => {
        console.log("Starting subscription auto-billing job...");

        const now = admin.firestore.Timestamp.now();

        try {
            const subscriptionsRef = db.collection("subscriptions");
            const dueSubscriptions = await subscriptionsRef
                .where("status", "==", "active")
                .where("nextBillingDate", "<=", now)
                .get();

            console.log(`Found ${dueSubscriptions.size} subscriptions due for billing`);

            const batch = db.batch();
            let invoicesCreated = 0;

            for (const subDoc of dueSubscriptions.docs) {
                const subscription = subDoc.data();
                const orgId = subscription.orgId;

                const invoiceRef = db.collection("invoices").doc();
                const invoiceNumber = `INV-${Date.now()}-${invoicesCreated + 1}`;

                const invoiceData = {
                    orgId,
                    customerId: subscription.customerId,
                    subscriptionId: subDoc.id,
                    number: invoiceNumber,
                    status: "sent",
                    items: [{
                        description: subscription.planName || "Subscription",
                        quantity: 1,
                        rate: subscription.amount || 0,
                        total: subscription.amount || 0,
                    }],
                    subtotal: subscription.amount || 0,
                    tax: 0,
                    total: subscription.amount || 0,
                    amountPaid: 0,
                    amountDue: subscription.amount || 0,
                    currency: subscription.currency || "USD",
                    dueDate: admin.firestore.Timestamp.fromDate(
                        new Date(Date.now() + 30 * 24 * 60 * 60 * 1000)
                    ),
                    createdAt: now,
                    sentAt: now,
                    autoGenerated: true,
                };

                batch.set(invoiceRef, invoiceData);

                const nextBillingDate = new Date(subscription.nextBillingDate.toDate());
                if (subscription.billingCycle === "yearly") {
                    nextBillingDate.setFullYear(nextBillingDate.getFullYear() + 1);
                } else {
                    nextBillingDate.setMonth(nextBillingDate.getMonth() + 1);
                }

                batch.update(subDoc.ref, {
                    nextBillingDate: admin.firestore.Timestamp.fromDate(nextBillingDate),
                    lastBilledAt: now,
                });

                invoicesCreated++;
            }

            await batch.commit();
            console.log(`Created ${invoicesCreated} invoices`);
            return null;
        } catch (error) {
            console.error("Error in subscription auto-billing:", error);
            throw error;
        }
    });
